version: "3.8"

services:
  web:
    build: ./web
    command: gunicorn -w 4 -b :5000 'server:app' --timeout 90
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    expose:
      - 5000
    restart: always
    volumes:
      - ./web/:/usr/src/app/

  llamacpp:
    image: ghcr.io/ggerganov/llama.cpp:server--b1-97bdd26
    command: -m /models/mistral-7b-instruct-v0.2.Q4_K_S.gguf -c 2048 --host 0.0.0.0 --port 8081 -cb --timeout 30 --parallel 2 -spf /models/systemPrompt.json
    expose:
      - 8081
    restart: always
    volumes:
      - ./models:/models

  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  puppeteer:
    build: puppeteer
    environment:
      APPNAME: Admin
      APPURL: http://web:5000/admin
    env_file:
      - ./.env

volumes:
  models:
  puppeteer:
